#!/usr/bin/env sh

# Speak a greeting, based on the time of day.

time="$(date +%H)";
name="$(id -F | grep -o -w '\w*')";

say "Hello $name.";
if [ "$time" -lt 12 ]; then
  say 'Good morning!';
elif [ "$time" -lt 17 ]; then
  say 'Good afternoon!';
else
  say 'Good evening!';
fi
