#!/usr/bin/env sh

# Speak a greeting, based on the time of day.

time="$(date +%H)";
name="$(id -F | grep -o -w '\w*')";
greeting="Hello $name.[[slnc 200]] Good";

if [ "$time" -lt 12 ]; then
  say "$greeting morning!";
elif [ "$time" -lt 17 ]; then
  say "$greeting afternoon!";
else
  say "$greeting evening!";
fi
